### ISSUE TITLE
erro de links no readme

### ISSUE THREAD

**Issue by isyuricunha** [Paula-Maia/paula-Maia#1]
e ai,

acredito que, talvez voce nao tenha percebido, mas, os links do seu readme estao errados (para suas redes e contatos), entao, tomei a iniciativa de te ajudar a arrumar

este seria seu codigo original, o qual voce pode consultar se funciona antes de realizar as alteracoes

```
  <a href="" target="_blank"><img src="https://img.shields.io/badge/-Instagram-%23E4405F?style=for-the-badge&logo=instagram&logoColor=white" target="_blank"></a>
 <a href="https://discord.gg/Paulamaia#1194" target="_blank"><img src="https://img.shields.io/badge/Discord-7289DA?style=for-the-badge&logo=discord&logoColor=white" target="_blank"></a> 
  <a href = "https://contagith@gmail.com"><img src="https://img.shields.io/badge/-Gmail-%23333?style=for-the-badge&logo=gmail&logoColor=white" target="_blank"></a>
  <a href="https://www.linkedin.com/in/paula-maia22" target="_blank"><img src="https://img.shields.io/badge/-LinkedIn-%230077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank"></a> 
 
  ![Snake animation](https://github.com/paula-Maia/paula-Maia/blob/output/github-contribution-grid-snake.svg)
```

agora, este seria o codigo corrigido, mas, devo fazer um adendo que, voce precisa colocar o seu link do instagram, pois, nao lhe procurei nessa rede

```
  <a href="coloqueSeuLinkAqui" target="_blank"><img src="https://img.shields.io/badge/-Instagram-%23E4405F?style=for-the-badge&logo=instagram&logoColor=white" target="_blank"></a>
 <a href="linkNaoFunciona" target="_blank"><img src="https://img.shields.io/badge/Discord-7289DA?style=for-the-badge&logo=discord&logoColor=white" target="_blank"></a> 
  <a href = "mailto:seuEmail@gmail.com"><img src="https://img.shields.io/badge/-Gmail-%23333?style=for-the-badge&logo=gmail&logoColor=white" target="_blank"></a>
  <a href="https://www.linkedin.com/in/paula-maia22" target="_blank"><img src="https://img.shields.io/badge/-LinkedIn-%230077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank"></a> 
 
  ![Snake animation](https://github.com/paula-Maia/paula-Maia/blob/output/github-contribution-grid-snake.svg)
```

em seu instagram, nao havia links

em seu discord, colocar o usuario nao funciona, voce precisa do ID, que pode ser encontrado dando um lookup na internet e/ou ativando o modo desenvolvedor nas configuracoes do discord e copiando o seu id clicando no seu perfil apos ativar o modo desenvolvedor, como por exemplo [https://discordapp.com/users/1018988240151253002](https://discordapp.com/users/1018988240151253002), que vai direto para o meu discord (voce é livre para tirar quaisquer duvidas)

no seu email, estava usando como se fosse um link, com https:/, mas o correto é usar o `mailto:SeuEmail`, e, o email tambem parecia se ficticio

o seu linkedin esta correto

saudacoes,
yuri

**Comment by isyuricunha** [comment]
repare que no `href` coloquei como exemplo o que voce deve por

**Comment by Paula-Maia** [comment]
Ah sim, eu só tava fazendo um teste ontem mesmo

Em qui., 2 de fev. de 2023 10:59, Yuri Cunha ***@***.***>
escreveu:

**Comment by Paula-Maia** [comment]
Obrigada pela preocupação, daqui a pouquinho eu vou arrumar:)

Em qui., 2 de fev. de 2023 12:01, Gabriele ***@***.***> escreveu:
